### PR TITLE
fix panic and filter on 'database/sql' package

### LINKED ISSUE #3: panic: runtime error: index out of range [0] with length 0
Running this tool `go vet -vettool=$(which execinquery) ./...` on favonia/cloudflare-ddns@f227115e85a54b211ef2792f8012b0e72eaa1063 gives the following error:

```
# github.com/favonia/cloudflare-ddns/internal/api_test
panic: runtime error: index out of range [0] with length 0

goroutine 9 [running]:
github.com/lufeee/execinquery.run.func1({0x6d5d38?, 0xc000184900})
	<redacted>/go/pkg/mod/github.com/lufeee/execinquery@v1.0.0/execinquery.go:45 +0x3ae
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc0006d0258, {0x0?, 0x81aae0?, 0x0?}, 0xc0009b2cc8)
	<redacted>/go/pkg/mod/golang.org/x/tools@v0.1.9/go/ast/inspector/inspector.go:77 +0x9a
github.com/lufeee/execinquery.run(0xc00062fee0)
	<redacted>/go/pkg/mod/github.com/lufeee/execinquery@v1.0.0/execinquery.go:27 +0x77
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
	<redacted>/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:355 +0x82e
sync.(*Once).doSlow(0x0?, 0x0?)
	/usr/lib/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/lib/go/src/sync/once.go:59
golang.org/x/tools/go/analysis/unitchecker.run.func5(0x81a920?)
	<redacted>/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:307 +0x1a5
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0x0?)
	<redacted>/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:367 +0x29
created by golang.org/x/tools/go/analysis/unitchecker.run.func6
	<redacted>/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:366 +0x47
```

PS: the README seems to miss the dollar sign in `go vet -vettool=$(which execinquery) ./...`.

### PR DESCRIPTION
**Pull request by ldez**
Fix #3

### CODE REVIEW

File: execinquery.go [hunk 1]
```diff
@@ -45,28 +57,35 @@ func run(pass *analysis.Pass) (interface{}, error) {
 			switch arg := n.Args[i].(type) {
```
Comment (favonia) [inline execinquery.go:57]: Maybe also adding this checking before `var s string`?
```go
			if i >= len(n.Args) {
				return
			}
```
I know this is impossible for the current `database/sql`, but I feel we should still check.

Comment (lufeee) [reply execinquery.go:57]: In the golang, the definition of the variable is different between `var s string` and `s := "AAAA"`
this code is only checking `s := "AAAA"` case.

**Comment by lufeee** [comment]
@ldez Thanks for fixing this bug.
LGTM

File: execinquery.go (hunk 1 above)
Comment (favonia) [reply execinquery.go:57]: No I was not talking about the variable `s`. I was proposing the following code, in addition to what @idez what already did:

```go
			// ...

			if i >= len(n.Args) {
				return
			}

			var s string
			switch arg := n.Args[i].(type) {

			// ...
```
The reason is that `n.Args[i]` will panic if `i >= en(n.Args[i])`. And the reason I propose putting the check before the line `var s string` is because the variable `s` is meaningful only later.

Comment (ldez) [reply execinquery.go:57]: the check is at the beginning of the function.

Comment (favonia) [reply execinquery.go:57]: Ah, sorry I somehow missed it.

Comment (favonia) [reply execinquery.go:57]: Wait, no, the check is still wrong...

**Comment by favonia** [comment]
The code does not fix all the problems because `i` was increased by one after `len(n.Args) < 1`. However, it is difficult to unmerge a PR, so let me start another PR.

File: execinquery.go (hunk 1 above)
Comment (ldez) [reply execinquery.go:57]: FYI: my login is ldez not idez

I will take a look
